spring.application.name=voucher
# ============ DATABASE CONFIGURATION ============ #
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/voucher
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
# ============ HIBERNATE CONFIGURATION =========== #
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true 
# ============ JWT CONFIGURATION ================= #
jwt.secret=QUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVphYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejAxMjM0NTY3ODl2b3VjaGVyc3ByaW5nYm9vdA==
jwt.expiration=86400000
jwt.refreshExpiration=604800000
# ======= SERVER CONFIGURATION ========= #
server.port=8080